DECLARE 
		CURRENT_HOST VARCHAR2(512);
		CURRENT_DOMAIN VARCHAR2(512);
		CURRENT_USERID VARCHAR2(512);
BEGIN
	SELECT SYS_CONTEXT('USERENV','OS_USER') INTO CURRENT_USERID FROM DUAL;
	SELECT SYS_CONTEXT('USERENV','HOST') INTO CURRENT_HOST FROM DUAL;
	SELECT SUBSTR(CURRENT_HOST, 0, INSTR(CURRENT_HOST, '\')) INTO CURRENT_DOMAIN FROM DUAL;
	
	UPDATE EMPLOYEES SET USERID = CURRENT_DOMAIN || CURRENT_USERID
	WHERE EMPLOYEEID = 2;
	
	UPDATE EMPLOYEES SET USERID = CURRENT_DOMAIN || 'qa-user' || CAST(EMPLOYEEID AS VARCHAR(5))
	WHERE EMPLOYEEID <> 2;
END;
/ 
