
CREATE OR REPLACE PROCEDURE CATEGORIESSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		CATEGORYID AS "CategoryID",
		CATEGORYNAME AS "CategoryName",
		DESCRIPTION AS "Description",
		PICTURE AS "Picture"
	FROM CATEGORIES;

END;
/

CREATE OR REPLACE PROCEDURE CATEGORIESUPDATE
(
	VCATEGORYID IN CATEGORIES.CATEGORYID%type,
	VCATEGORYNAME IN CATEGORIES.CATEGORYNAME%type,
	VDESCRIPTION IN CATEGORIES.DESCRIPTION%type,
	VPICTURE IN CATEGORIES.PICTURE%type
)
IS
BEGIN
	UPDATE CATEGORIES
	SET
		CATEGORYID	= VCATEGORYID,
		CATEGORYNAME	= VCATEGORYNAME,
		DESCRIPTION	= VDESCRIPTION,
		PICTURE	= VPICTURE
	WHERE
		CATEGORYID = VCATEGORYID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE CATEGORIESINSERT
(
	VCATEGORYID IN CATEGORIES.CATEGORYID%type,
	VCATEGORYNAME IN CATEGORIES.CATEGORYNAME%type,
	VDESCRIPTION IN CATEGORIES.DESCRIPTION%type,
	VPICTURE IN CATEGORIES.PICTURE%type
)
IS
BEGIN


	INSERT
	INTO CATEGORIES
	(
		CATEGORYID,
		CATEGORYNAME,
		DESCRIPTION,
		PICTURE
	)
	VALUES
	(
		VCATEGORYID,
		VCATEGORYNAME,
		VDESCRIPTION,
		VPICTURE
	);
END;
/

CREATE OR REPLACE PROCEDURE CATEGORIESDELETE
(
	VCATEGORYID IN CATEGORIES.CATEGORYID%type
)
IS
BEGIN

	DELETE	FROM CATEGORIES
	WHERE
		CATEGORYID = VCATEGORYID;

END;
/
