
CREATE OR REPLACE PROCEDURE CUSTOMERDEMOGRAPHICSSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		CUSTOMERTYPEID,
		CUSTOMERDESC
	FROM CUSTOMERDEMOGRAPHICS;

END;
/

CREATE OR REPLACE PROCEDURE CUSTOMERDEMOGRAPHICSUPDATE
(
	VCUSTOMERTYPEID IN CUSTOMERDEMOGRAPHICS.CUSTOMERTYPEID%type,
	VCUSTOMERDESC IN CUSTOMERDEMOGRAPHICS.CUSTOMERDESC%type
)
IS
BEGIN
	UPDATE CUSTOMERDEMOGRAPHICS
	SET
		CUSTOMERTYPEID	= VCUSTOMERTYPEID,
		CUSTOMERDESC	= VCUSTOMERDESC
	WHERE
		CUSTOMERTYPEID = VCUSTOMERTYPEID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE CUSTOMERDEMOGRAPHICSINSERT
(
	VCUSTOMERTYPEID IN CUSTOMERDEMOGRAPHICS.CUSTOMERTYPEID%type,
	VCUSTOMERDESC IN CUSTOMERDEMOGRAPHICS.CUSTOMERDESC%type
)
IS
BEGIN


	INSERT
	INTO CUSTOMERDEMOGRAPHICS
	(
		CUSTOMERTYPEID,
		CUSTOMERDESC
	)
	VALUES
	(
		VCUSTOMERTYPEID,
		VCUSTOMERDESC
	);
END;
/

CREATE OR REPLACE PROCEDURE CUSTOMERDEMOGRAPHICSDELETE
(
	VCUSTOMERTYPEID IN CUSTOMERDEMOGRAPHICS.CUSTOMERTYPEID%type
)
IS
BEGIN

	DELETE	FROM CUSTOMERDEMOGRAPHICS
	WHERE
		CUSTOMERTYPEID = VCUSTOMERTYPEID;

END;
/
