
CREATE OR REPLACE PROCEDURE CUSTOMERCUSTOMERDEMOSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		CUSTOMERID AS "CustomerID",
		CUSTOMERTYPEID AS "CustomerTypeID"
	FROM CUSTOMERCUSTOMERDEMO;

END;
/



CREATE OR REPLACE PROCEDURE CUSTOMERCUSTOMERDEMOINSERT
(
	VCUSTOMERID IN CUSTOMERCUSTOMERDEMO.CUSTOMERID%type,
	VCUSTOMERTYPEID IN CUSTOMERCUSTOMERDEMO.CUSTOMERTYPEID%type
)
IS
BEGIN


	INSERT
	INTO CUSTOMERCUSTOMERDEMO
	(
		CUSTOMERID,
		CUSTOMERTYPEID
	)
	VALUES
	(
		VCUSTOMERID,
		VCUSTOMERTYPEID
	);
END;
/

CREATE OR REPLACE PROCEDURE CUSTOMERCUSTOMERDEMODELETE
(
	VCUSTOMERID IN CUSTOMERCUSTOMERDEMO.CUSTOMERID%type,
	VCUSTOMERTYPEID IN CUSTOMERCUSTOMERDEMO.CUSTOMERTYPEID%type
)
IS
BEGIN

	DELETE	FROM CUSTOMERCUSTOMERDEMO
	WHERE
		CUSTOMERID = VCUSTOMERID AND
		CUSTOMERTYPEID = VCUSTOMERTYPEID;

END;
/
