
CREATE OR REPLACE PROCEDURE ORDERDETAILSSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		ORDERID,
		PRODUCTID,
		UNITPRICE,
		QUANTITY,
		DISCOUNT
	FROM ORDERDETAILS;

END;
/

CREATE OR REPLACE PROCEDURE ORDERDETAILSUPDATE
(
	VORDERID IN ORDERDETAILS.ORDERID%type,
	VPRODUCTID IN ORDERDETAILS.PRODUCTID%type,
	VUNITPRICE IN ORDERDETAILS.UNITPRICE%type,
	VQUANTITY IN ORDERDETAILS.QUANTITY%type,
	VDISCOUNT IN ORDERDETAILS.DISCOUNT%type
)
IS
BEGIN
	UPDATE ORDERDETAILS
	SET
		ORDERID	= VORDERID,
		PRODUCTID	= VPRODUCTID,
		UNITPRICE	= VUNITPRICE,
		QUANTITY	= VQUANTITY,
		DISCOUNT	= VDISCOUNT
	WHERE
		ORDERID = VORDERID
	AND	PRODUCTID = VPRODUCTID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE ORDERDETAILSINSERT
(
	VORDERID IN ORDERDETAILS.ORDERID%type,
	VPRODUCTID IN ORDERDETAILS.PRODUCTID%type,
	VUNITPRICE IN ORDERDETAILS.UNITPRICE%type,
	VQUANTITY IN ORDERDETAILS.QUANTITY%type,
	VDISCOUNT IN ORDERDETAILS.DISCOUNT%type
)
IS
BEGIN


	INSERT
	INTO ORDERDETAILS
	(
		ORDERID,
		PRODUCTID,
		UNITPRICE,
		QUANTITY,
		DISCOUNT
	)
	VALUES
	(
		VORDERID,
		VPRODUCTID,
		VUNITPRICE,
		VQUANTITY,
		VDISCOUNT
	);
END;
/

CREATE OR REPLACE PROCEDURE ORDERDETAILSDELETE
(
	VORDERID IN ORDERDETAILS.ORDERID%type,
	VPRODUCTID IN ORDERDETAILS.PRODUCTID%type
)
IS
BEGIN

	DELETE	FROM ORDERDETAILS
	WHERE
		ORDERID = VORDERID AND
		PRODUCTID = VPRODUCTID;

END;
/
