
CREATE OR REPLACE PROCEDURE SUPPLIERSSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		SUPPLIERID,
		COMPANYNAME,
		CONTACTNAME,
		CONTACTTITLE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		PHONE,
		FAX,
		HOMEPAGE
	FROM SUPPLIERS;

END;
/

CREATE OR REPLACE PROCEDURE SUPPLIERSUPDATE
(
	VSUPPLIERID IN SUPPLIERS.SUPPLIERID%type,
	VCOMPANYNAME IN SUPPLIERS.COMPANYNAME%type,
	VCONTACTNAME IN SUPPLIERS.CONTACTNAME%type,
	VCONTACTTITLE IN SUPPLIERS.CONTACTTITLE%type,
	VADDRESS IN SUPPLIERS.ADDRESS%type,
	VCITY IN SUPPLIERS.CITY%type,
	VREGION IN SUPPLIERS.REGION%type,
	VPOSTALCODE IN SUPPLIERS.POSTALCODE%type,
	VCOUNTRY IN SUPPLIERS.COUNTRY%type,
	VPHONE IN SUPPLIERS.PHONE%type,
	VFAX IN SUPPLIERS.FAX%type,
	VHOMEPAGE IN SUPPLIERS.HOMEPAGE%type
)
IS
BEGIN
	UPDATE SUPPLIERS
	SET
		SUPPLIERID	= VSUPPLIERID,
		COMPANYNAME	= VCOMPANYNAME,
		CONTACTNAME	= VCONTACTNAME,
		CONTACTTITLE	= VCONTACTTITLE,
		ADDRESS	= VADDRESS,
		CITY	= VCITY,
		REGION	= VREGION,
		POSTALCODE	= VPOSTALCODE,
		COUNTRY	= VCOUNTRY,
		PHONE	= VPHONE,
		FAX	= VFAX,
		HOMEPAGE	= VHOMEPAGE
	WHERE
		SUPPLIERID = VSUPPLIERID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE SUPPLIERSINSERT
(
	VSUPPLIERID IN SUPPLIERS.SUPPLIERID%type,
	VCOMPANYNAME IN SUPPLIERS.COMPANYNAME%type,
	VCONTACTNAME IN SUPPLIERS.CONTACTNAME%type,
	VCONTACTTITLE IN SUPPLIERS.CONTACTTITLE%type,
	VADDRESS IN SUPPLIERS.ADDRESS%type,
	VCITY IN SUPPLIERS.CITY%type,
	VREGION IN SUPPLIERS.REGION%type,
	VPOSTALCODE IN SUPPLIERS.POSTALCODE%type,
	VCOUNTRY IN SUPPLIERS.COUNTRY%type,
	VPHONE IN SUPPLIERS.PHONE%type,
	VFAX IN SUPPLIERS.FAX%type,
	VHOMEPAGE IN SUPPLIERS.HOMEPAGE%type
)
IS
BEGIN


	INSERT
	INTO SUPPLIERS
	(
		SUPPLIERID,
		COMPANYNAME,
		CONTACTNAME,
		CONTACTTITLE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		PHONE,
		FAX,
		HOMEPAGE
	)
	VALUES
	(
		VSUPPLIERID,
		VCOMPANYNAME,
		VCONTACTNAME,
		VCONTACTTITLE,
		VADDRESS,
		VCITY,
		VREGION,
		VPOSTALCODE,
		VCOUNTRY,
		VPHONE,
		VFAX,
		VHOMEPAGE
	);
END;
/

CREATE OR REPLACE PROCEDURE SUPPLIERSDELETE
(
	VSUPPLIERID IN SUPPLIERS.SUPPLIERID%type
)
IS
BEGIN

	DELETE	FROM SUPPLIERS
	WHERE
		SUPPLIERID = VSUPPLIERID;

END;
/
