
CREATE OR REPLACE PROCEDURE TERRITORIESSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		TERRITORYID,
		TERRITORYDESCRIPTION,
		REGIONID
	FROM TERRITORIES;

END;
/

CREATE OR REPLACE PROCEDURE TERRITORIESUPDATE
(
	VTERRITORYID IN TERRITORIES.TERRITORYID%type,
	VTERRITORYDESCRIPTION IN TERRITORIES.TERRITORYDESCRIPTION%type,
	VREGIONID IN TERRITORIES.REGIONID%type
)
IS
BEGIN
	UPDATE TERRITORIES
	SET
		TERRITORYID	= VTERRITORYID,
		TERRITORYDESCRIPTION	= VTERRITORYDESCRIPTION,
		REGIONID	= VREGIONID
	WHERE
		TERRITORYID = VTERRITORYID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE TERRITORIESINSERT
(
	VTERRITORYID IN TERRITORIES.TERRITORYID%type,
	VTERRITORYDESCRIPTION IN TERRITORIES.TERRITORYDESCRIPTION%type,
	VREGIONID IN TERRITORIES.REGIONID%type
)
IS
BEGIN


	INSERT
	INTO TERRITORIES
	(
		TERRITORYID,
		TERRITORYDESCRIPTION,
		REGIONID
	)
	VALUES
	(
		VTERRITORYID,
		VTERRITORYDESCRIPTION,
		VREGIONID
	);
END;
/

CREATE OR REPLACE PROCEDURE TERRITORIESDELETE
(
	VTERRITORYID IN TERRITORIES.TERRITORYID%type
)
IS
BEGIN

	DELETE	FROM TERRITORIES
	WHERE
		TERRITORYID = VTERRITORYID;

END;
/
