CREATE TABLE CUSTOMERS 
(
    CUSTOMERID varchar(5) NOT NULL,
    COMPANYNAME varchar(40) NOT NULL,
    CONTACTNAME varchar(30),
    CONTACTTITLE varchar(30),
    ADDRESS varchar(60),
    CITY varchar(15),
    REGION varchar(15),
    POSTALCODE varchar(10),
    COUNTRY varchar(15),
    PHONE varchar(24),
    FAX varchar(24),
    PRIMARY KEY(CUSTOMERID)
);

CREATE INDEX CUSTOMERS_CITY_IDX ON CUSTOMERS (CITY);
CREATE INDEX CUSTOMERS_COMPANYNAME_IDX ON CUSTOMERS (COMPANYNAME);
CREATE INDEX CUSTOMERS_POSTALCODE_IDX ON CUSTOMERS (POSTALCODE);
CREATE INDEX CUSTOMERS_REGION_IDX ON CUSTOMERS (REGION);
