-- SET THE CREATED USER PASS AND ALLOW LOGIN RIGHTS
DECLARE 
	DBNAME VARCHAR(30);
BEGIN
	SELECT SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') INTO DBNAME FROM DUAL;
	EXECUTE IMMEDIATE 'ALTER USER ' || DBNAME || ' IDENTIFIED BY TheSecret';
	EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || DBNAME;
END;
/