CREATE TABLE EMPLOYEES 
(
    EMPLOYEEID decimal NOT NULL,
    LASTNAME varchar(20) NOT NULL,
    FIRSTNAME varchar(10) NOT NULL,
    EMPLOYEETITLE varchar(30),
    TITLEOFCOURTESY varchar(25),
    BIRTHDATE date,
    HIREDATE date,
    ADDRESS varchar(60),
    CITY varchar(15),
    REGION varchar(15),
    POSTALCODE varchar(10),
    COUNTRY varchar(15),
    HOMEPHONE varchar(24),
    EXTENSION varchar(4),
    PHOTOPATH varchar(255),
    NOTES varchar(1000),
    REPORTSTO decimal,
    PRIMARY KEY(EMPLOYEEID)
);

CREATE INDEX EMPLOYEES_LASTNAME_IDX (LASTNAME) ON EMPLOYEES;

CREATE INDEX EMPLOYEES_POSTALCODE_IDX (POSTALCODE) ON EMPLOYEES;
