
CREATE OR REPLACE PROCEDURE CUSTOMERSSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		CUSTOMERID,
		COMPANYNAME,
		CONTACTNAME,
		CONTACTTITLE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		PHONE,
		FAX
	FROM CUSTOMERS;

END;
/

CREATE OR REPLACE PROCEDURE CUSTOMERSUPDATE
(
	VCUSTOMERID IN CUSTOMERS.CUSTOMERID%type,
	VCOMPANYNAME IN CUSTOMERS.COMPANYNAME%type,
	VCONTACTNAME IN CUSTOMERS.CONTACTNAME%type,
	VCONTACTTITLE IN CUSTOMERS.CONTACTTITLE%type,
	VADDRESS IN CUSTOMERS.ADDRESS%type,
	VCITY IN CUSTOMERS.CITY%type,
	VREGION IN CUSTOMERS.REGION%type,
	VPOSTALCODE IN CUSTOMERS.POSTALCODE%type,
	VCOUNTRY IN CUSTOMERS.COUNTRY%type,
	VPHONE IN CUSTOMERS.PHONE%type,
	VFAX IN CUSTOMERS.FAX%type
)
IS
BEGIN
	UPDATE CUSTOMERS
	SET
		CUSTOMERID	= VCUSTOMERID,
		COMPANYNAME	= VCOMPANYNAME,
		CONTACTNAME	= VCONTACTNAME,
		CONTACTTITLE	= VCONTACTTITLE,
		ADDRESS	= VADDRESS,
		CITY	= VCITY,
		REGION	= VREGION,
		POSTALCODE	= VPOSTALCODE,
		COUNTRY	= VCOUNTRY,
		PHONE	= VPHONE,
		FAX	= VFAX
	WHERE
		CUSTOMERID = VCUSTOMERID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE CUSTOMERSINSERT
(
	VCUSTOMERID IN CUSTOMERS.CUSTOMERID%type,
	VCOMPANYNAME IN CUSTOMERS.COMPANYNAME%type,
	VCONTACTNAME IN CUSTOMERS.CONTACTNAME%type,
	VCONTACTTITLE IN CUSTOMERS.CONTACTTITLE%type,
	VADDRESS IN CUSTOMERS.ADDRESS%type,
	VCITY IN CUSTOMERS.CITY%type,
	VREGION IN CUSTOMERS.REGION%type,
	VPOSTALCODE IN CUSTOMERS.POSTALCODE%type,
	VCOUNTRY IN CUSTOMERS.COUNTRY%type,
	VPHONE IN CUSTOMERS.PHONE%type,
	VFAX IN CUSTOMERS.FAX%type
)
IS
BEGIN


	INSERT
	INTO CUSTOMERS
	(
		CUSTOMERID,
		COMPANYNAME,
		CONTACTNAME,
		CONTACTTITLE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		PHONE,
		FAX
	)
	VALUES
	(
		VCUSTOMERID,
		VCOMPANYNAME,
		VCONTACTNAME,
		VCONTACTTITLE,
		VADDRESS,
		VCITY,
		VREGION,
		VPOSTALCODE,
		VCOUNTRY,
		VPHONE,
		VFAX
	);
END;
/

CREATE OR REPLACE PROCEDURE CUSTOMERSDELETE
(
	VCUSTOMERID IN CUSTOMERS.CUSTOMERID%type
)
IS
BEGIN

	DELETE	FROM CUSTOMERS
	WHERE
		CUSTOMERID = VCUSTOMERID;

END;
/
