
CREATE OR REPLACE PROCEDURE EMPLOYEESSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		EMPLOYEEID,
		LASTNAME,
		FIRSTNAME,
		TITLE,
		TITLEOFCOURTESY,
		BIRTHDATE,
		HIREDATE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		HOMEPHONE,
		EXTENSION,
		NOTES,
		REPORTSTO,
		PHOTOPATH,
		USERID
	FROM EMPLOYEES;

END;
/

CREATE OR REPLACE PROCEDURE EMPLOYEESUPDATE
(
	VEMPLOYEEID IN EMPLOYEES.EMPLOYEEID%type,
	VLASTNAME IN EMPLOYEES.LASTNAME%type,
	VFIRSTNAME IN EMPLOYEES.FIRSTNAME%type,
	VTITLE IN EMPLOYEES.TITLE%type,
	VTITLEOFCOURTESY IN EMPLOYEES.TITLEOFCOURTESY%type,
	VBIRTHDATE IN EMPLOYEES.BIRTHDATE%type,
	VHIREDATE IN EMPLOYEES.HIREDATE%type,
	VADDRESS IN EMPLOYEES.ADDRESS%type,
	VCITY IN EMPLOYEES.CITY%type,
	VREGION IN EMPLOYEES.REGION%type,
	VPOSTALCODE IN EMPLOYEES.POSTALCODE%type,
	VCOUNTRY IN EMPLOYEES.COUNTRY%type,
	VHOMEPHONE IN EMPLOYEES.HOMEPHONE%type,
	VEXTENSION IN EMPLOYEES.EXTENSION%type,
	VNOTES IN EMPLOYEES.NOTES%type,
	VREPORTSTO IN EMPLOYEES.REPORTSTO%type,
	VPHOTOPATH IN EMPLOYEES.PHOTOPATH%type,
	VUSERID IN EMPLOYEES.USERID%type
)
IS
BEGIN
	UPDATE EMPLOYEES
	SET
		EMPLOYEEID	= VEMPLOYEEID,
		LASTNAME	= VLASTNAME,
		FIRSTNAME	= VFIRSTNAME,
		TITLE	= VTITLE,
		TITLEOFCOURTESY	= VTITLEOFCOURTESY,
		BIRTHDATE	= VBIRTHDATE,
		HIREDATE	= VHIREDATE,
		ADDRESS	= VADDRESS,
		CITY	= VCITY,
		REGION	= VREGION,
		POSTALCODE	= VPOSTALCODE,
		COUNTRY	= VCOUNTRY,
		HOMEPHONE	= VHOMEPHONE,
		EXTENSION	= VEXTENSION,
		NOTES	= VNOTES,
		REPORTSTO	= VREPORTSTO,
		PHOTOPATH	= VPHOTOPATH,
		USERID	= VUSERID
	WHERE
		EMPLOYEEID = VEMPLOYEEID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE EMPLOYEESINSERT
(
	VEMPLOYEEID IN EMPLOYEES.EMPLOYEEID%type,
	VLASTNAME IN EMPLOYEES.LASTNAME%type,
	VFIRSTNAME IN EMPLOYEES.FIRSTNAME%type,
	VTITLE IN EMPLOYEES.TITLE%type,
	VTITLEOFCOURTESY IN EMPLOYEES.TITLEOFCOURTESY%type,
	VBIRTHDATE IN EMPLOYEES.BIRTHDATE%type,
	VHIREDATE IN EMPLOYEES.HIREDATE%type,
	VADDRESS IN EMPLOYEES.ADDRESS%type,
	VCITY IN EMPLOYEES.CITY%type,
	VREGION IN EMPLOYEES.REGION%type,
	VPOSTALCODE IN EMPLOYEES.POSTALCODE%type,
	VCOUNTRY IN EMPLOYEES.COUNTRY%type,
	VHOMEPHONE IN EMPLOYEES.HOMEPHONE%type,
	VEXTENSION IN EMPLOYEES.EXTENSION%type,
	VNOTES IN EMPLOYEES.NOTES%type,
	VREPORTSTO IN EMPLOYEES.REPORTSTO%type,
	VPHOTOPATH IN EMPLOYEES.PHOTOPATH%type,
	VUSERID IN EMPLOYEES.USERID%type
)
IS
BEGIN


	INSERT
	INTO EMPLOYEES
	(
		EMPLOYEEID,
		LASTNAME,
		FIRSTNAME,
		TITLE,
		TITLEOFCOURTESY,
		BIRTHDATE,
		HIREDATE,
		ADDRESS,
		CITY,
		REGION,
		POSTALCODE,
		COUNTRY,
		HOMEPHONE,
		EXTENSION,
		NOTES,
		REPORTSTO,
		PHOTOPATH,
		USERID
	)
	VALUES
	(
		VEMPLOYEEID,
		VLASTNAME,
		VFIRSTNAME,
		VTITLE,
		VTITLEOFCOURTESY,
		VBIRTHDATE,
		VHIREDATE,
		VADDRESS,
		VCITY,
		VREGION,
		VPOSTALCODE,
		VCOUNTRY,
		VHOMEPHONE,
		VEXTENSION,
		VNOTES,
		VREPORTSTO,
		VPHOTOPATH,
		VUSERID
	);
END;
/

CREATE OR REPLACE PROCEDURE EMPLOYEESDELETE
(
	VEMPLOYEEID IN EMPLOYEES.EMPLOYEEID%type
)
IS
BEGIN

	DELETE	FROM EMPLOYEES
	WHERE
		EMPLOYEEID = VEMPLOYEEID;

END;
/
