
CREATE OR REPLACE PROCEDURE ORDERSSELECT
(
    RESULTSET OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTSET FOR
	SELECT
		ORDERID,
		CUSTOMERID,
		EMPLOYEEID,
		ORDERDATE,
		REQUIREDDATE,
		SHIPPEDDATE,
		SHIPVIA,
		FREIGHT,
		SHIPNAME,
		SHIPADDRESS,
		SHIPCITY,
		SHIPREGION,
		SHIPPOSTALCODE,
		SHIPCOUNTRY
	FROM ORDERS;

END;
/

CREATE OR REPLACE PROCEDURE ORDERSUPDATE
(
	VORDERID IN ORDERS.ORDERID%type,
	VCUSTOMERID IN ORDERS.CUSTOMERID%type,
	VEMPLOYEEID IN ORDERS.EMPLOYEEID%type,
	VORDERDATE IN ORDERS.ORDERDATE%type,
	VREQUIREDDATE IN ORDERS.REQUIREDDATE%type,
	VSHIPPEDDATE IN ORDERS.SHIPPEDDATE%type,
	VSHIPVIA IN ORDERS.SHIPVIA%type,
	VFREIGHT IN ORDERS.FREIGHT%type,
	VSHIPNAME IN ORDERS.SHIPNAME%type,
	VSHIPADDRESS IN ORDERS.SHIPADDRESS%type,
	VSHIPCITY IN ORDERS.SHIPCITY%type,
	VSHIPREGION IN ORDERS.SHIPREGION%type,
	VSHIPPOSTALCODE IN ORDERS.SHIPPOSTALCODE%type,
	VSHIPCOUNTRY IN ORDERS.SHIPCOUNTRY%type
)
IS
BEGIN
	UPDATE ORDERS
	SET
		ORDERID	= VORDERID,
		CUSTOMERID	= VCUSTOMERID,
		EMPLOYEEID	= VEMPLOYEEID,
		ORDERDATE	= VORDERDATE,
		REQUIREDDATE	= VREQUIREDDATE,
		SHIPPEDDATE	= VSHIPPEDDATE,
		SHIPVIA	= VSHIPVIA,
		FREIGHT	= VFREIGHT,
		SHIPNAME	= VSHIPNAME,
		SHIPADDRESS	= VSHIPADDRESS,
		SHIPCITY	= VSHIPCITY,
		SHIPREGION	= VSHIPREGION,
		SHIPPOSTALCODE	= VSHIPPOSTALCODE,
		SHIPCOUNTRY	= VSHIPCOUNTRY
	WHERE
		ORDERID = VORDERID
;
	
	
END;
/



CREATE OR REPLACE PROCEDURE ORDERSINSERT
(
	VORDERID IN ORDERS.ORDERID%type,
	VCUSTOMERID IN ORDERS.CUSTOMERID%type,
	VEMPLOYEEID IN ORDERS.EMPLOYEEID%type,
	VORDERDATE IN ORDERS.ORDERDATE%type,
	VREQUIREDDATE IN ORDERS.REQUIREDDATE%type,
	VSHIPPEDDATE IN ORDERS.SHIPPEDDATE%type,
	VSHIPVIA IN ORDERS.SHIPVIA%type,
	VFREIGHT IN ORDERS.FREIGHT%type,
	VSHIPNAME IN ORDERS.SHIPNAME%type,
	VSHIPADDRESS IN ORDERS.SHIPADDRESS%type,
	VSHIPCITY IN ORDERS.SHIPCITY%type,
	VSHIPREGION IN ORDERS.SHIPREGION%type,
	VSHIPPOSTALCODE IN ORDERS.SHIPPOSTALCODE%type,
	VSHIPCOUNTRY IN ORDERS.SHIPCOUNTRY%type
)
IS
BEGIN


	INSERT
	INTO ORDERS
	(
		ORDERID,
		CUSTOMERID,
		EMPLOYEEID,
		ORDERDATE,
		REQUIREDDATE,
		SHIPPEDDATE,
		SHIPVIA,
		FREIGHT,
		SHIPNAME,
		SHIPADDRESS,
		SHIPCITY,
		SHIPREGION,
		SHIPPOSTALCODE,
		SHIPCOUNTRY
	)
	VALUES
	(
		VORDERID,
		VCUSTOMERID,
		VEMPLOYEEID,
		VORDERDATE,
		VREQUIREDDATE,
		VSHIPPEDDATE,
		VSHIPVIA,
		VFREIGHT,
		VSHIPNAME,
		VSHIPADDRESS,
		VSHIPCITY,
		VSHIPREGION,
		VSHIPPOSTALCODE,
		VSHIPCOUNTRY
	);
END;
/

CREATE OR REPLACE PROCEDURE ORDERSDELETE
(
	VORDERID IN ORDERS.ORDERID%type
)
IS
BEGIN

	DELETE	FROM ORDERS
	WHERE
		ORDERID = VORDERID;

END;
/
